### ISSUE TITLE
Create Number module

### ISSUE THREAD

**Issue by rxaviers** [globalizejs/globalize#200]
**Implementation**
Parse
- `Globalize.parseNumber( value )` (#248)

Format

`Globalize.formatNumber( value [, options] )`
- **options** (mimics [ECMA-402 options](http://www.ecma-international.org/ecma-402/1.0/#sec-11.4));
  - style: "decimal", "percent", "currency";
  - currency;
  - currencyDisplay: "decimal", "currency", or "percent";
  - [x] minimumFractionDigits, maximumFractionDigits; (#213)
  - [x] minimumIntegerDigits; (#213)
  - [x] minimumSignificantDigits, maximumSignificantDigits; (#214)
  - [x] numberingSystem; (#249)
  - [x] round: arbitrary round options ("ceil", "floor", "round" default, "truncate");
  - [x] useGrouping; (#216)
- [x] Other Numbering Systems (native, traditional, finance) [specs](http://www.unicode.org/reports/tr35/tr35-numbers.html#otherNumberingSystems); (#249)

**Functional tests**
- [x] #190
- [x] #191

**Documentation**
- [x] Update README; (#213)

---

Docs:
- [UTS #35: Unicode LDML, Part 3: Numbers](http://www.unicode.org/reports/tr35/tr35-numbers.html)
- ECMA-402
- [CLDR Translation Guidelines: Number Patterns](http://cldr.unicode.org/translation/number-patterns)
- [CLDR Translation Guidelines: Number Symbols](http://cldr.unicode.org/translation/number-symbols)

Evaluate API/implementation:
- [ECMA-402 Intl.NumberFormat](http://www.ecma-international.org/ecma-402/1.0/#sec-11.4)
- [ICU Number Format](http://icu-project.org/apiref/icu4c/classicu_1_1NumberFormat.html)
- [Dojo Number Format](http://dojotoolkit.org/reference-guide/1.9/dojo/number.html#format)
- [TwitterCldr for JavaScript](https://github.com/twitter/twitter-cldr-js)
- [TwitterCldr for Ruby](https://github.com/twitter/twitter-cldr-rb)
- [Google Closure Number Format](http://docs.closure-library.googlecode.com/git/class_goog_i18n_NumberFormat.html)
- [CLDR::Number for Perl](https://github.com/perl-cldr/cldr-number-perl5), (@patch)
- [Mediawiki Language Numbers](https://github.com/wikimedia/mediawiki-core/blob/master/resources/mediawiki.language/mediawiki.language.numbers.js#L210-L238) (@santhoshtr)

**Comment by nemobis** [comment]
Very nice to see that Globalize has adopted some CLDR data and that some MediaWiki code has been of use! We're keeping track of the sinergies at https://www.mediawiki.org/wiki/Globalize

FYI, libraries for CLDR and i18n handling are being split out of the MediaWiki codebase, e.g. recently https://www.mediawiki.org/wiki/CLDRPluralRuleParser . If you happened to need some more splitting, please file a request https://phabricator.wikimedia.org/maniphest/task/create/
