### ISSUE TITLE
No "invariant" culture?

### ISSUE THREAD

**Issue by blq** [globalizejs/globalize#25]
What was the motivation for dropping the "invariant" culture?  (commit 099e13a73a5236354aeed5c93919765fc9d20283)

Even if not being set as the default culture, I think it would be useful to maintain symmetry with  for example .NET that exposes it.

// Fredrik Blomqvist

**Comment by n8allan** [comment]
An example of where this would be particularly nice is for a distributed system, where a given collation (even if it isn't comprehensive) could be depended on to be present and consistent.  This is a fairly common need.
