### ISSUE TITLE
Simple Javascript demo?

### ISSUE THREAD

**Issue by michael-fischer** [globalizejs/globalize#349]
Hopefully this is something that is easy to fix.  I am trying to evolve the <a href="https://github.com/jquery/globalize/tree/master/examples/plain-javascript">Hello World (Plain Javascript)</a> tutorial to be more dynamic similar to what is outlined in <A href="https://github.com/jquery/globalize/blob/master/doc/cldr.md">Example of loading it dynamically</a> under how do I get CLDR data.  The merged code looks something like the following.

``` javascript
$.when(
  $.get("/Scripts/cldr/data/main/en-US/ca-gregorian.json"),
  $.get("/Scripts/cldr/data/supplemental/likelySubtags.json"),
  $.get("/Scripts/cldr/data/supplemental/timeData.json"),
  $.get("/Scripts/cldr/data/supplemental/weekData.json")
).then(function () {

    // Normalize $.get results, we only need the JSON, not the request statuses.
    return [].slice.apply(arguments, [0]).map(function (result) {
        return result[0];
    });
}).then(Globalize.load).then(function () {
    // Instantiate "en".
    var en = Globalize( "en-US" );
    // Use Globalize to format dates.
    document.getElementById( "date" ).innerHTML = en.formatDate( new Date(), {
      datetime: "medium"
    });
    // Use Globalize to format numbers.
    document.getElementById( "number" ).innerHTML = en.formatNumber( 12345.6789 );
    // Use Globalize to format a message with plural inflection.
    var pluralData = {
      one: "{0} result",
      other: "{0} results"
    };
    document.getElementById( "plural-0" ).innerHTML = en.formatPlural( 0, pluralData );
    document.getElementById( "plural-1" ).innerHTML = en.formatPlural( 1, pluralData );
    document.getElementById( "plural-2" ).innerHTML = en.formatPlural( 2, pluralData );
    document.getElementById( "requirements" ).style.display = "none";
    document.getElementById( "demo" ).style.display = "block";
});
```

This code errors in the call to `Globalize.load` when it checks for IsPlainObject.  It tries to compare the JSON string to `"[object Object]"'` I am a back end developer moving into javascript so was hoping you could verify that I am on the right path and my assumptions about a new [to me] language are valid.  Perhaps offer a hint as to the changes that need to be made.  I tried to look at the test suites but they use other technologies.

Thanks,

Michael Fischer

**Comment by clazette** [comment]
I could be wrong but this appears to be associated with Globalize.load in globalize.js. This call Cldr.load.apply( Cldr, arguments ); negates the fact that you executed this in the example:

`// Normalize $.get results, we only need the JSON, not the request statuses.
    return [].slice.apply(arguments, [0]).map(function (result) {
        return result[0];
    });
'
because you just turn around and use arguments which is an array of the files retrieved each containing another array with 3 elements. This causes Cldr.load.apply to fail the isPlainObject check.

I posted what I believe is the same issue - [https://github.com/rxaviers/cldrjs/issues/45](https://github.com/rxaviers/cldrjs/issues/45)

I just found this post looking for something else.

**Comment by haklanje385** [comment]
This did trick for me:

        $.when(
            $.get("cldr/supplemental/likelySubtags.json", null, null, "json"),
            $.get("cldr/main/en/numbers.json", null, null, "json"),
            $.get("cldr/main/en/ca-gregorian.json", null, null, "json")
        ).then(function () {
            return [].slice.apply( arguments, [ 0 ] ).map(function( result ) {
                Globalize.load(result[0]);
            })
        }).then(function () {
            Globalize.locale(locale)
        });`

**Comment by rxaviers** [comment]
All, if anyone finds anything wrong in globalize code, docs, and/or examples, please create another issue with details. So far I'm considering this a closed issue.
