### ISSUE TITLE
Number: parse literals

### ISSUE THREAD

**Issue by rxaviers** [globalizejs/globalize#353]
Handle literals when parsing numbers. E.g.,

```
Globalize.parseNumber("-$1,214.12", { pattern: "'$'#,##0.##" });
```

Test:
- [x] #443
- [x] #457
- [x] #46
- [x] #492
- [x] #587
- [x] #644

References:
- http://www.unicode.org/reports/tr35/tr35-numbers.html#Special_Pattern_Characters
- analogous to `src/date/token*` and `src/date/parse*`. Look at https://github.com/jquery/globalize/blob/0b85f34dc1a47bc2b9c6f8bbed15a7b7b8f4752f/src/date/tokenizer.js#L369-L376.
  - http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Format_Patterns

**Comment by lijunle** [comment]
Hi, @rxaviers This bug is open on year 2014. Any updates on it?

**Comment by rxaviers** [comment]
The project is out of resources and is relying on external contribution to get this feature implemented.

Having said that, this feature is still open to be included. If you're willing to contribute it, I can provide further any guidance you may need to get up to speed. Thanks.

**Comment by lijunle** [comment]
@rxaviers Could you provide some resources and ideas about how to implement this? Besides, do you have some workaround on this?

**Comment by rxaviers** [comment]
The workaround is to do any parsing at user land and pass a number only to numberParser, which isn't great.

I've updated one resource link in the description. Please, let me know what you think after going through them.

The files that will need change is `src/number/parse.js`. The changes should be analogous to `src/date/{parse, tokenizer}*`.

Please, just let me know if you have any further questions.

**Comment by rxaviers** [comment]
Edit: One file that will need change is `src/number/parse.js`. The changes should be analogous to `src/date/{parse, tokenizer}*`.

**Comment by rxaviers** [comment]
PR #644 in place :)

**Comment by rxaviers** [comment]
PR #656 in place :) (EDITED)
