### ISSUE TITLE
E_PAR_OUT_OF_RANGE: Parameter `minimumFractionDigits` has value `NaN` out of range [0, 20].

### ISSUE THREAD

**Issue by dpolivy** [globalizejs/globalize#472]
Locale: ja-JP
Currency Code: JPY

Calling `currencyFormatter` with the following as `options` results in the exception in the title:

``` javascript
    {
        maximumFractionDigits: 0
    }
```

It seems that in this case, the logic at this line might not be correct? `minimumFractionDigits` is undefined, and persists that way.
https://github.com/jquery/globalize/blob/master/src/number/format-properties.js#L81

I haven't had time to dig in more to see if this is a data, cldrjs, or code issue, but hopefully it's an easy fix.

This is blocking Japanese users on our site as it just blows up trying to format currency.

**Comment by rxaviers** [comment]
Note to self: the root cause is `minimumFractionDigits` not being initialized when the number raw pattern has no decimal part, e.g., `{raw: "0"}`.

PS: Specifically, the `JPY` currency (independently of the used locale) has no decimal digits. Therefore, it uses a number pattern with no such part.
