### ISSUE TITLE
parseDate returns AM datetime in zh and zh-Hant despite Chinese PM characters

### ISSUE THREAD

**Issue by jspeaker** [globalizejs/globalize#509]
When evaluating amPm, only "pm" is used to determine if the datetime is in the PM. Because "afternoon" exists in zh and zh-Hant, and the Chinese characters for it are exactly the same as those used for "PM", and it alphabetically comes first, it sets the amPm variable to "afternoon" rather than "pm" and therefore incorrectly does not add 12 hours.

**Comment by rxaviers** [comment]
WIP Fix #508

**Comment by rxaviers** [comment]
WIP Fix #508. It misses unit test only.
