### ISSUE TITLE
Inconsistencies when parsing date with fixed format

### ISSUE THREAD

**Issue by globalizer** [globalizejs/globalize#538]
I'm trying to understand the ruleset when it comes to parsing dates with a fixed format.

If I use the format yyyyMMdd, and try to parse the value 20151102, then null is returned. According to issue 444, this is because yyyy means year with full padding, meaning that the full value 20151102 is interpreted as a year. Fine.

But if I instead use the format dMyyyy with the value 12112015, the date "2015-11-12" (here in ISO8601) is returned, despite the fact that this value should have the same ambiguity as the example above.

According to the [reference](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table), "d" and "M" is used to show the minimum number, which can be either 1 or 2 digits. So according to this, the value 12112015 parsed with the format dMyyyy could have the following valid interpretations (again, dates below are in ISO8601 format):
- 2015-11-12
- 12015-01-12
- 112015-02-01
- Also, With the same reasoning that 20151102 parsed using the format yyyyMMdd results in year 20151102, it would make sense that 12112015 parsed with the format dMyyyy  could mean year 12112015. 

It would appear that the parsing is made in some greedy fashion, but I can't find any documentation on this behavior and it seems like it's not the expected behavior of a date parser.

So I have the following issues here (overlapping):
- Why does jquery/globalize assume that d and M means 2 digits each when the reference says that it can be 1 or 2? 
- If 20151102 parsed with yyyyMMdd results in year 20151102, why doesn't parsing 12112015 with dMyyyy result in year 12112015?

**Comment by rxaviers** [comment]
Hi @globalizer, thanks for filing this issue.

In CLDR, all patterns (in every locales) that involves year, month, and day always include a kind of separator (e.g., `d/M/y`, or `dd.MM.y`, `y年M月d日`, `d-M-y`) to avoid such redundancies. The primary concern of Globalize is parsing anything that is in CLDR.

Although I understand the pattern of your question is valid, I think the root question is why would someone use a redundant pattern in the first place?

**Comment by rxaviers** [comment]
I'm closing this bug. If you believe this is still a problem, please post a comment. Thanks
