### ISSUE TITLE
CLDR dayPeriods

### ISSUE THREAD

**Issue by Mottie** [globalizejs/globalize#544]
CLDR data provides a variety of day periods:

``` js
new Cldr( "en" ).main([ "dates/calendars/gregorian/dayPeriods", "format", "abbreviated" ]);
/* outputs: 
{
  afternoon1: "in the afternoon",
  am: "AM",
  am-alt-variant: "am",
  evening1: "in the evening",
  midnight: "midnight",
  morning1: "in the morning",
  night1: "at night",
  noon: "noon",
  pm: "PM",
  pm-alt-variant: "pm"
}
*/
```

The `skeleton` option can be used to format the time, but it always includes either the `am` or `pm` settings since most formats use "a". In the spec you can use "B" in the skeleton, but it only uses `night1` and possibly `morning1`? "b" is also allowed to set "noon" and "midnight" specific times.

I would like to propose adding a `dayPeriod` option which would allow use of `C` ([per spec](http://www.unicode.org/reports/tr35/tr35-dates.html#Date_Field_Symbol_Table)); additional options maybe be needed to further customize the day period string used, maybe something similar to this:

``` js
var opts = {
  skeleton : "hm",
  dayPeriod : "C", // "a", "b", "B" or "C" (per spec) for custom day periods
  // the below option only works with "B" or "C"  set in dayPeriod
  setPeriods : {
    "00:00" : "midnight",
    "00:01" : "night1",
    "06:00" : "morning1",
    "12:00" : "noon",
    "12:01" : "afternoon1",
    "18:00" : "evening1",
    "21:00" : "night1"
  }
};
Globalize( "en" ).dateFormatter( opts )( new Date( 2010, 10, 1, 17, 55 ) );
// outputs: "5:55 in the afternoon"
Globalize( "en" ).dateFormatter( opts )( new Date( 2010, 10, 1, 19, 55 ) );
// outputs: "7:55 in the evening"
```

**Comment by Mottie** [comment]
I made a bunch of updates to my initial post...

After finding [this page on day periods](http://www.unicode.org/cldr/charts/latest/supplemental/day_periods.html), I think one more parameter should be included:

```js
amSetpoint : 6
```

which is the time when the code switches from using `pmPeriod` to `amPeriod`.

**Comment by Mottie** [comment]
I didn't include a documentation update to `date-formatter.md` because I have a feeling that the content would need to be modified, so I'll include it here.

I planned on adding the following *after* the "raw" option

----

The following options(s) can be used along with any of the above settings to
change the day period text.

> **dayPeriod**
>
> String value indicating the day period format to use, eg. `"a"`, `"B"` or `"C"`
> The default `"a"` sets the day period code to either "am" or "pm".
> Using either "B" or "C" in this option will allow use of expanded day period codes,
> as determined by the `setPeriod` option, eg. `{ time: "full", dayPeriod: "C" }`.

> **setPeriod**
>
> Object containing sets of matching start time (`hh:mm`) and [day period code](http://www.unicode.org/cldr/charts/latest/supplemental/day_periods.html)
> values which allows setting a different message depending on a time greater than
> or equal to the start time.
> ```
{
  time: "full",
  dayPeriod: "C",
  setPeriods : {
    "00:00" : "midnight",
    "00:01" : "night1",
    "06:00" : "morning1",
    "12:00" : "noon",
    "12:01" : "afternoon1",
    "18:00" : "evening1",
    "21:00" : "night1"
  }
}
```
> e.g. `{ skeleton: "hm", dayPeriod: "C", setPeriods: {...} }`
>
> | locale | setPeriods varies |
> | --- | --- |
> | *en* | `"12:00 noon"` (`"noon"`) |
> | *zh* | `"晚上8:00"` (`"morning2"`) |
> | *es* | `"12:00 de la tarde"` (`"evening1"`) |
> | *ar* | `"١:٠٠ بعد الظهر"` (`"afternoon2"`) |
> | *pt* | `"7:00 da manhã"` (`"morning1"`) |
>
> \* Note \* The start time & day period code ([ref](http://www.unicode.org/cldr/charts/latest/supplemental/day_periods.html)) in `setPeriod` vary with locale.
> It needs to be manually added because this data is not is not currently
> available in the CLDR JSON data.

**Comment by rxaviers** [comment]
It's very unfortunate that the project didn't have enough resources to review your issue and PR for so long. Sorry

**Comment by rxaviers** [comment]
@Mottie you did a great work, sorry it was lost in limbo by the lack of activity in the project during this time. If either @Mottie or someone else is willing to resurrect this implementation, it would be good to evaluate `dayPeriod` and `setPeriod` options. For the first (`dayPeriod`), I'm interested to know what other implementations do (e.g., ICU); for the second one (`setPeriod`), I think there should be no such option and instead we should gather this information from CLDR supplemental.

**Comment by Mottie** [comment]
Hi @rxaviers!

No problem, I can update this PR, but I just noticed that the current tests are failing in the master branch... at least on my system.

> Date Parse - should parse date according to passed timeZone in various datetime patterns
> Message: null
> Actual: "Sun Mar 12 2017 05:00:00 GMT-0500 (Central Daylight Time)"
> Expected: "Sun Mar 12 2017 04:00:00 GMT-0500 (Central Daylight Time)"
> dateParseWithTimezone@http://localhost:9001/unit/date/parse.js:46:16
> http://localhost:9001/unit/date/parse.js:1210:30
> run@http://localhost:9001/external/qunit/qunit/qunit.js:895:32
> http://localhost:9001/external/qunit/qunit/qunit.js:1024:14
> process@http://localhost:9001/external/qunit/qunit/qunit.js:583:24
> next@http://localhost:9001/external/qunit/qunit/qunit.js:570:10
>
> Date Parse - should parse date according to passed timeZone in various datetime patterns
> Message: null
> Actual: "Sun Mar 12 2017 06:00:00 GMT-0500 (Central Daylight Time)"
> Expected: "Sun Mar 12 2017 05:00:00 GMT-0500 (Central Daylight Time)"
> dateParseWithTimezone@http://localhost:9001/unit/date/parse.js:46:16
> http://localhost:9001/unit/date/parse.js:1219:30
> run@http://localhost:9001/external/qunit/qunit/qunit.js:895:32
> http://localhost:9001/external/qunit/qunit/qunit.js:1024:14
> process@http://localhost:9001/external/qunit/qunit/qunit.js:583:24
> next@http://localhost:9001/external/qunit/qunit/qunit.js:570:10

Anyway, I'll go ahead and update the PR.

**Comment by Mottie** [comment]
Oops, I totally glossed over your questions... sorry!

> For the first (dayPeriod), I'm interested to know what other implementations do (e.g., ICU);

I'm not familiar enough with ICU to answer this question, but from looking at [this ICU demo page](http://demo.icu-project.org/icu-bin/locexp?d_=en&_=pt) for Portuguese, it is showing only "AM" and "PM".

> for the second one (setPeriod), I think there should be no such option and instead we should gather this information from CLDR supplemental.

You're right! When I first submitted this PR, I could not find the period data inside of CLDR... I see now it is in the supplemental dayPeriods.json file. I'll make this change to the PR.

----
I've updated the PR, and now I see errors from the date-format code I added. They don't appear when I run the tests locally, and now I am seeing number format property test failures. I think I need to delete and download the repository again.

**Comment by rxaviers** [comment]
Awesome, thanks @Mottie 

> I can update this PR, but I just noticed that the current tests are failing in the master branch... at least on my system... Anyway, I'll go ahead and update the PR.

Sure go ahead, I can help you investigate the failing tests later...

> I'm not familiar enough with ICU to answer this question, but from looking at this ICU demo page for Portuguese, it is showing only "AM" and "PM".

> You're right! When I first submitted this PR, I could not find the period data inside of CLDR... I see now it is in the supplemental dayPeriods.json file. I'll make this change to the PR.

Awesome.

> I've updated the PR, and now I see errors from the date-format code I added. They don't appear when I run the tests locally, and now I am seeing number format property test failures. I think I need to delete and download the repository again.

Alternatively, try to rebase:

```
git fetch origin
git checkout <your working branch>
git rebase origin/master
```

**Comment by rxaviers** [comment]
> I'm not familiar enough with ICU to answer this question, but from looking at this ICU demo page for Portuguese, it is showing only "AM" and "PM".

I think that instead creating a new dateFormatter option, using the skeleton `C` is the way to go:
- See the `C` format/field at http://www.unicode.org/reports/tr35/tr35-dates.html#dfst-hour . "For example, with `"Cmm"`, 18:00 could appear as `"6:00 in the afternoon"`".
- Also see ICU `"Cmm"` examples for [en](http://demo.icu-project.org/icu4jweb/flexTest.jsp?pat=Cmm&_=en) and for [zh](http://demo.icu-project.org/icu4jweb/flexTest.jsp?pat=Cmm&_=zh). Note that each locale has a preferred day period choice.

In that line of thought, we should be able to do that:

```js
Globalize('zh').formatDate(new Date(), {skeleton: 'Cmm'})
// > 清晨5:43 (i.e., found "Bh:mm" as best pattern)
```

**Comment by Mottie** [comment]
That sounds great! I'll try to work on that later today when I get some time.

I was wondering, why isn't [`cldr-data`](https://github.com/rxaviers/cldr-data-npm) added as a dependency? I would think it is a better option than the `cldr-data-downloader` dev dependency.

**Comment by rxaviers** [comment]
> That sounds great! I'll try to work on that later today when I get some time.

Excellent.

> I was wondering, why isn't cldr-data added as a dependency? I would think it is a better option than the cldr-data-downloader dev dependency.

The cldr-data-downloader dev dependency is there simply due to tests and bower is actually managing the dependency. That was coded in a time where npm didn't support flattening dependencies, now It's time to move to npm completely.

The cldr-data isn't a direct dependency, because developers can actually load CLDR from any source, not necessarily from cldr-data.

**Comment by stukalin** [comment]
@rxaviers not sure if this one was closed automatically but the real fix is yet to come.
