### ISSUE TITLE
Currency formatter failing for JPY

### ISSUE THREAD

**Issue by cahuja** [globalizejs/globalize#565]
Here is the currencyFormatter that is failing - 
Globalize.currencyFormatter ( "JPY" , { maximumFractionDigits : 2 } );

Uncaught minimumFractionDigits: E_PAR_OUT_OF_RANGE: Parameter `minimumFractionDigits` has value `NaN` out of range [0, 20].createError @ app.js:8204

However, the following call - 
Globalize.currencyFormatter ( "JPY" );
results in no errors.

It seems like setting maximumFractionDigits for JPY causes the following error by wiping out other properties that should have default values

**Comment by cahuja** [comment]
In this case, setting both maximumFractionDigits and minimumFractionDigits fixes the problem. Should this still be an issue?

**Comment by cahuja** [comment]
Also, for what it's worth, I tried this on a few currencies before I stumbled upon the problem. Its not an issue with USD, GBP, EUR, INR. I tried all of these and the formatter worked, but broke with JPY.

**Comment by rxaviers** [comment]
Will get back to it when I have more time, but for the record I think it's related to the fact that the rules for the JPY currency modifies the `maximumFractionDigits` and `minimumFractionDigits` to `0`.

**Comment by jeevajevi** [comment]
Hi All,

   I am using globalize.js for currency formatting. Through this link [https://github.com/jquery/globalize/tree/master/examples/plain-javascript](url) i can able to achieve USD. But i need for USD and JPY. Please any one help to solve this issue.
