### ISSUE TITLE
Negative test for invalid currency - formatCurrency

### ISSUE THREAD

**Issue by lwelti** [globalizejs/globalize#588]
is two questions in one :)

1) do you have a negative test for formatCurrency ?

2) what happens if I pass an invalid/not supported currency? for example LTL ?

thanks in advance.

**Comment by rxaviers** [comment]
Hi @lwelti 


> 1. do you have a negative test for formatCurrency ?

We have negative tests for parameter assertions.

> 2. what happens if I pass an invalid/not supported currency? for example LTL ?

It will throw the following missing CLDR error. It's not possible to know if user forgot to load the right data or if the code is invalid.

    Error: E_MISSING_CLDR: Missing required CLDR content `main/en/numbers/currencies/LAS/symbol`.

Closing... Please, feel free to post additional comments if you're looking for another specific negative tests. Thanks

By the way, tests are at https://github.com/globalizejs/globalize/tree/master/test
