### ISSUE TITLE
parseNumber issue with grouping seperator removal

### ISSUE THREAD

**Issue by Masaroth** [globalizejs/globalize#616]
Hi

There seems to be an issue with how parseNumber currently deals with any grouping separators in the value trying to be parsed.

In say the "en-GB" locale . is the decimal separator and , is the grouping separator. If the user accidentally uses the grouping separator as the decimal separator I would expect the value not to parse but it does causing higher numbers to go through than the user would expect.

Globalize.parseNumber("15,40") whilst the user may have meant to enter 15.40 globalize will treat this value as 1540 which would be incorrect and I would like it not to parse.

Globalize.parseNumber("2.000,50") with the decimal and grouping completely mixed up fails the regex number check and returns NaN which is what i would have expected in the first example as well.

Is there a configuration option i have somehow missed to stop this or is the case the regex needs updating to reject that value? From what I can see the problem is in number.js lines 984-995 as if it passes the regex check as a number it will remove all grouping separators from the value, thus the higher value than intended being returned.

**Comment by rxaviers** [comment]
This is fixed in globalize 1.2.2.

```
> Globalize('en-GB').parseNumber("15,40")
NaN
> Globalize('en-GB').parseNumber("2.000,50")
NaN
> Globalize('en-GB').parseNumber("2,000.50")
2000.5
> 
```
