### ISSUE TITLE
parseNumber() can fail for strings with group separator

### ISSUE THREAD

**Issue by mikolodziejczyk** [globalizejs/globalize#619]
When the group separator is a space and the input string contains group separator(s), parseNumber() fails.
For example:
`Globalize("pl").parseNumber('1 234') // => NaN, should be 1234.`
Internally, the number regex fails to recognize this as a valid number.
https://github.com/jquery/globalize/blob/master/src/number/parse.js#L71

**Comment by rxaviers** [comment]
Thanks for filing the bug. This is fixed.
