### ISSUE TITLE
Node v0.10 installs cldr-data (peer dependencies) automatically

### ISSUE THREAD

**Issue by Setogit** [globalizejs/globalize#628]
The issue is three fold:
- Node v0.10 does not understand the concept of "peer dependency" and always installs.
- Node v0.10 does not have a concept of "flat dependency resolution" implemented by npm v3.x and install multiple copies of cldr-data.
- On Node v0.10, `globalize` installation takes huge amount of unnecessary space and time.

A directly related issue was reported and some mitigation ideas are here: https://github.com/strongloop/strong-globalize/issues/54

**Comment by rxaviers** [comment]
Hi @Setogit, thanks for filing this issue.

I'm open for ideas to improve this scenario. It's important that a solution doesn't break any of the design points summarized in https://github.com/jquery/globalize/#why-globalize.

One solution is https://github.com/rxaviers/cldr-data-npm/issues/28.

Ideas?

**Comment by rxaviers** [comment]
We dropped cldr-data as peer dependency #647, so I believe this is fixed. Please, just let me know if you still find any problem.
