### ISSUE TITLE
cldr-data as peer dependency?

### ISSUE THREAD

**Issue by rxaviers** [globalizejs/globalize#638]
Does listing cldr-data as peer dependency make sense? We should rething...

By the time it was adopted there was only cldr-data (i.e., there was no unicode official github/npm repo) and npm didn't support flatten dependencies. Defining cldr-data as peer-dependency was a way of having two libraries using CLDR data to reuse the same cldr-data module (e.g., globalize and cldrjs).

One additional goal of defining cldr-data as a peer dependency was to avoid that applications use incompatible CLDR x Globalize versions. In theory, a CLDR schema change could break compatibility with Globalize. Also, new CLDR rules could appear in future releases and Globalize include support for such features, therefore Globalize could update its CLDR compatible range via the peer dependency.

The existing problem is that applications can use different CLDR sources, e.g., the [Unicode modules](https://github.com/unicode-cldr/cldr-core) or local downloaded/processed data. And there's nothing wrong with doing so, because in Globalize we actually empower such choices. We have cldr-data as a convenience, but it's not mandatory. This is basically the existing conflict. In one hand, we rely on cldr-data module to define peer dependency, but in the other hand we have users that don't use it.

**Comment by kborchers** [comment]
Seems like moving to official unicode repo makes sense to me. I do not claim to be an expert here though so take my opinion as less important than others.

**Comment by jzaefferer** [comment]
With no time to do the research myself: How would this affect usage? Does it get easier? Or more effort for the enduser? A before/after example would help a lot. If there's no difference for the user, moving to official repos and deprecating workarounds is always a good strategy.

**Comment by rubennorte** [comment]
An additional problem having `cldr-data` as a peer dependency is that we must install it and download all the locale data (~200MB) even if we only use a very small amount of it. That could be a problem in projects with only local dependencies (docker, etc.).

If it weren't a peer dependency we could include the portions we wanted in our projects and not install the package, saving a lot of space.

**Comment by rxaviers** [comment]
EDIT description:

Does listing cldr-data as peer dependency make sense? We should rething...

By the time it was adopted there was only cldr-data (i.e., there was no unicode official github/npm repo) and npm didn't support flatten dependencies. Defining cldr-data as peer-dependency was a way of having two libraries using CLDR data to reuse the same cldr-data module (e.g., globalize and cldrjs).

One additional goal of defining cldr-data as a peer dependency was to avoid that applications use incompatible CLDR x Globalize versions. In theory, a CLDR schema change could break compatibility with Globalize. Also, new CLDR rules could appear in future releases and Globalize include support for such features, therefore Globalize could update its CLDR compatible range via the peer dependency.

The existing problem is that applications can use different CLDR sources, e.g., the [Unicode modules](https://github.com/unicode-cldr/cldr-core) or local downloaded/processed data. And there's nothing wrong with doing so, because in Globalize we actually empower such choices. We have cldr-data as a convenience, but it's not mandatory. This is basically the existing conflict. In one hand, we rely on cldr-data module to define peer dependency, but in the other hand we have users that don't use it.

**Comment by rxaviers** [comment]
> That could be a problem in projects with only local dependencies (docker, etc.).

@rubennorte, true.

**Comment by rxaviers** [comment]
> @jzaefferer 

Good questions... 

> How would this affect usage? Does it get easier? Or more effort for the enduser? A before/after example would help a lot.

For cldr-data users... Nothing changes except that they can install any cldr-data version with no compatibility verification for Globalize. In practice, there was none verification anyway (`>=25.x` means all existing cldr-data releases). The biggest impact will be not being able to make use of such feature in future releases.

For non cldr-data users... They'll be able to install globalize with no unnecessary "missing cldr-data peer dependency" warnings.

> If there's no difference for the user, moving to official repos and deprecating workarounds is always a good strategy.

Actually, the proposal is to step back on using CLDR data as peer dependency (either via cldr-data or something else) because of the problems presented above.

**Comment by jzaefferer** [comment]
Can you outline the actual changes? If its trivial to make the change, dump the diff into a gist or a WIP PR?

**Comment by rxaviers** [comment]
```diff
diff --git a/package.json b/package.json
index ad4f41f..46fce51 100644
--- a/package.json
+++ b/package.json
@@ -67,9 +67,6 @@
   "dependencies": {
     "cldrjs": "0.4.4"
   },
-  "peerDependencies": {
-    "cldr-data": ">=25"
-  },
   "devDependencies": {
     "grunt": "0.4.5",
     "grunt-check-dependencies": "0.6.0",
```

**Comment by rxaviers** [comment]
This is a very small change and I plan to release it as a patch release. Feedbacks are welcome.

**Comment by jzaefferer** [comment]
Our Getting Started example uses cldr-data:
```js
var Globalize = require( "globalize" );
Globalize.load( require( "cldr-data" ).entireSupplemental() );
Globalize.load( require( "cldr-data" ).entireMainFor( "en", "es" ) );

Globalize("en").formatDate(new Date());
// > "11/27/2015"

Globalize("es").formatDate(new Date());
// > "27/11/2015"
```
If someone only installs globalize (ignoring the instruction to also install cldr-data), this would fail. Having the peerDependency in place might help. But if it does more damage by annoying anyone using an alternative to loading CLDR, then I agree that we should drop it.

**Comment by rxaviers** [comment]
Thanks for reviewing @jzaefferer.

> If someone only installs globalize (ignoring the instruction to also install cldr-data), this would fail

Yeap. I've updated the PR to include a comment emphasizing it uses the optional `cldr-data` module. Please, let me know if you have additional ideas.

> But if it does more damage by annoying anyone using an alternative to loading CLDR, then I agree that we should drop it.

Excellent.

**Comment by jzaefferer** [comment]
Where's the PR?

**Comment by rxaviers** [comment]
Now, there's a PR #647 :). PS: There was a branch only.
