### ISSUE TITLE
Consider moving this repo to globalizejs/globalize

### ISSUE THREAD

**Issue by rxaviers** [globalizejs/globalize#645]
Globalize satellite projects like globalize-compiler, globalize-webpack-plugin, react-globalize, and others are spread in different orgs.

Some team members and I are considering to move Globalize (and those other projects above) into @globalizejs for improved organization. :) It also helps clarifying the project has no technical dependency on jQuery (the project).

The plan is to make the move within days... Feedbacks are welcome.

**Comment by jzaefferer** [comment]
Would it also host cldrjs?

**Comment by rxaviers** [comment]
Yeap, it probably makes sense too.

**Comment by kborchers** [comment]
> Would it also host cldrjs?

> Yeap, it probably makes sense too.

Just keep in mind that only projects under JSF copyright can use the CLA so we will need to either transfer projects to the Foundation as part of the greater Globalize project if they are not already or they will need to be excluded from the CLA which is not ideal if it lives in this org.
