### ISSUE TITLE
Can we reduce npm package size?

### ISSUE THREAD

**Issue by rxaviers** [globalizejs/globalize#649]
- Examples are responsible for 3.7M.
- Temporary `dist/.build` for another ~1M.

**Comment by rxaviers** [comment]
Examples are responsible for 3.7M. They are usually helpful for development, but are generally useless in an npm installation. We could remove them from the npm package. 

Temporary `dist/.build` for another ~1M. We should definitely remove them from npm package and any other distribution.

**Comment by jzaefferer** [comment]
In a way, examples are part of the documentation, which is useful to include. I don't follow how they end up at 3.7 MB though. Maybe that's nested node_modules that you had locally when you published, and npm just published them along with everything else? If that's the issue, we should definitely exclude those nested node_modules.

**Comment by rxaviers** [comment]
Jörn, you're correct, just found the culprit `examples/app-bower-grunt-requirejs/bower_components`. The release script could assert those aren't present.

- [ ] Release script to rm any examples `node_modules` or `bower_components`.

**Comment by jzaefferer** [comment]
Probably simpler would be adding those to `.gitignore` (or `.npmignore`, if necessary).

**Comment by rxaviers** [comment]
Good point.

**Comment by rxaviers** [comment]
These files were already in `.gitignore` and are correctly being ignored by `git`, but not by `npm`. It seems to be a `npm` bug npm/npm#7264.

**Comment by jzaefferer** [comment]
Can it be worked around using explicit `.npmignore`?

**Comment by rxaviers** [comment]
I believe not since the npm-linked issue is about `.npmignore` too. Anyway, I think it's awful to have to duplicate .gitignore.

**Comment by jzaefferer** [comment]
Could try to remove the nested `.gitignore` files and pull everything up into the main one.
