### ISSUE TITLE
Globalize circular dependency errors

### ISSUE THREAD

**Issue by akatsak** [globalizejs/globalize#654]
I have decided to use globalize with ReactNative and faced the same errors as in https://github.com/joshswan/react-native-globalize/issues/3. In cldrjs it was fixed in https://github.com/rxaviers/cldrjs/issues/53. As far as I have understood a problem in cyclic dependences. The author of react-native-globalize has solved it in his fork globalize.

**Comment by rxaviers** [comment]
Thanks for filing this issue. It's worth mentioning it's not a problem for node or npm, but it seems to be a problem for some bundlers. The change is quick, let's make it in here as well. Feel free to submit a PR. Thanks.

**Comment by akatsak** [comment]
Remains a riddle why Facebook developers have written own bundler without any configurability. Perhaps to make us stronger). And i'm not the first time faced with this and assume that it happens in those who do not use babel.
