### ISSUE TITLE
German standard Date format

### ISSUE THREAD

**Issue by DamirUtje** [globalizejs/globalize#661]
I'm using the cldr version 30.0.2 lib. and the German standard Date format seems to be wrong 👎 

standard format should be => "dd.MM.yyyy"

ca-generic.json & ca-gregorian.json => "dd.MM.yy"

see:
"dateFormats": {
              "full": "EEEE, d. MMMM y G",
              "long": "d. MMMM y G",
              "medium": "dd.MM.y G",
              "short": "dd.MM.yy GGGGG"
            }

What is the reason for this issue and is it possible for u to change this in the next version ? 

Thanks
Damir

**Comment by rxaviers** [comment]
Hi @DamirUtje thanks for bringing this up, although I didn't understand what **standard** date you're referring to. The default pattern for formatDate is `{skeleton: 'yMd'}`, which corresponds to `'d.M.y'` in German.

The `{date: "short"}` corresponds to the `'dd.MM.yy'` pattern you mention. If you believe CLDR data should be fixed, there's http://unicode.org/cldr/trac/search. I recommend making a search there first to check if someone has reported the same issue you observe. By the way, why do you believe this should be `"dd.MM.yyyy"`?

**Comment by DamirUtje** [comment]
Hello @rxaviers , thanks for your reply. I will follow your advise. 

The reason why my pc operation systems (windows, linux) use this pattern "dd.MM.yyyy" to show current date in the task bar: 

"The format dd.mm.yyyy [..] is the traditional German date format. [..] Since 2006, the old format (d)d.(m)m.(yy)yy is allowed again as alternative to the yyyy-mm-dd format .."

Look here: 
https://en.wikipedia.org/wiki/Date_format_by_country

Thanks
Damir

**Comment by rxaviers** [comment]
@DamirUtje, be advised that you can use Globalize as follows (to format a date using `'dd.mm.yyyy'` in German):

```js
Globalize('de').formatDate(new Date(), {skeleton: 'yMMdd'})
'06.01.2017'
```

Important: this same skeleton might not work on some other locales until #271 is implemented though.

If you need any help in your request to CLDR, let me know. Having said that, it's still confusing to me what's your proposal, i.e., which of [these patterns](https://github.com/unicode-cldr/cldr-dates-modern/blob/19fb1d8ef2b5a0b588c581b7a2c06f21b9fdd1df/main/en/ca-gregorian.json#L322-L383) do you want them to change.

**Comment by DamirUtje** [comment]
@rxaviers   skeleton: 'yMMdd' doesn't work for me .. when i change the browser default language from german to "en-GB" or  "en" , my webApp crashes .. I am using a localized DevExpress widget, so i need more than only the german formatting

If i use `skeleton: 'yMd'` the result is "d.M.yyyy" instead of "dd.MM.yyyy" .. 

It seems that there is a misunderstanding relating to standardized date format and i hope that this issue can be fixed in the next version.
