### ISSUE TITLE
Unable to get query to work with globalizejs and requirejs

### ISSUE THREAD

**Issue by theisner** [globalizejs/globalize#665]
Hi,
I am trying to get the above to work. I have configured the following:
requirejs.config(
{
	baseUrl: '/vendor',
	paths:
	{
		// Globalize dependencies paths.
		'cldr': 'cldrjs/dist/cldr',
		// Unicode CLDR JSON data.
		'cldr-data': 'cldr-data',
		// require.js plugin we'll use to fetch CLDR JSON content.
		'json': 'requirejs-plugins/src/json',
		// text is json's dependency.
		'text': 'requirejs-text/text',
		// Globalize.
		'globalize': 'globalize/dist/globalize',
		// jQuery
		'jquery': 'jquery/dist/jquery',
		// jQuery-ui
		'jquery-ui': 'jquery-ui',
		// Moment
		'moment': 'moment/moment',
		// fullcalendar
		'fullcalendar': 'fullcalendar/dist/fullcalendar',
		// FOSrouting
		'fosrouter': '../bundles/fosjsrouting/js/router',
		// FOSroutes
		'fosroutes': '../bundles/fosjsrouting/js/fos_js_routes'
	}
});
require([
	'jquery',
	'cldr',
	'json',
	'text',
	'globalize',
	// CLDR content.
	"json!cldr-data/main/en/ca-gregorian.json",
	"json!cldr-data/main/en/currencies.json",
	"json!cldr-data/main/en/dateFields.json",
	"json!cldr-data/main/en/numbers.json",
	"json!cldr-data/main/en/units.json",
	"json!cldr-data/supplemental/currencyData.json",
	"json!cldr-data/supplemental/likelySubtags.json",
	"json!cldr-data/supplemental/plurals.json",
	"json!cldr-data/supplemental/timeData.json",
	"json!cldr-data/supplemental/weekData.json",
	// Extend Globalize with Date and Number modules.
	"globalize/currency",
	"globalize/date",
	"globalize/message",
	"globalize/number",
	"globalize/plural",
	"globalize/relative-time",
	"globalize/unit",
	'fosrouter',
	'moment',
	'fullcalendar'
], function($, Globalize, enGregorian, enCurrencies, enDateFields, enNumbers, enUnits, currencyData, likelySubtags, pluralsData, timeData, weekData, messages)
{
	'use strict';
	$.ajaxSetup(
	{
		cache: false
	});
	$(function()
	{ ...

This runs directly into an issue in line 3855 of jQuery.js with the following error message: 
json: E_INVALID_PAR_TYPE: {"expected":"Plain Object","name":"json"}

**Comment by rxaviers** [comment]
Please, please post a question to [StackOverflow with the "javascript-globalize" tag](http://stackoverflow.com/tags/javascript-globalize) instead. Alternatively, check our [amd-bower](https://github.com/globalizejs/globalize/tree/master/examples/amd-bower) example for AMD usage.
