### ISSUE TITLE
1.x equivalent to `Globalize.culture().calendar[":"]` from 0.x

### ISSUE THREAD

**Issue by Retsam** [globalizejs/globalize#668]
I'm trying to migrate some code from globalize 0.x to 1.x, and I've run across code that relies on `Globalize.culture().calendar[":"]` to determine the delimiter between parts of a time.  So far I haven't been able to find any such equivalent in the CLDR data.  

Is there an equivalent that I've missed?  Or a way to reliably calculate an equivalent?

**Comment by rxaviers** [comment]
Those time parts (as any other literals) are simply part of the pattern, for example: https://github.com/unicode-cldr/cldr-dates-modern/blob/master/main/es-US/ca-gregorian.json#L341

Why does the application need access to that info? To add styles / markups to it? If so, the correct solution is in this line: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts. I'm open to support formatToParts in globalize. PR welcome :yellow_heart:

**Comment by rxaviers** [comment]
Closing in favor of #678
