### ISSUE TITLE
Error: E_MISSING_MESSAGE: Missing required message content for message with variables.

### ISSUE THREAD

**Issue by lidanbj** [globalizejs/globalize#671]
I came across bellow message.
Error: E_MISSING_MESSAGE: Missing required message content ` hi, {0} ` when run UTs with Karma.
In karma I use react-globalize-webpack-plugins for webpack to build. as bellow

plugins: [
        new GlobalizePlugin({
          production: false,
          developmentLocale: 'en',
          supportedLocales: ['en'],
          messages: 'src/nls/locales/[locale].json',
          writeMessages: false,
          output: 'i18n/[locale].js'
        }),
      ],

Code to call :
Globalize.messageFormatter('hi, {0}')("dear");

when run UT the error message at the top would returned. The issue would not happen for these key which does not have variables. like

Globalize.messageFormatter('hi)();

**Comment by lidanbj** [comment]
BTW, it seems the react-webpack-plugin would translate  hi,{0}  to hi,(0):hi,{0} . But it can work on the main code with same react-webpack-plugin setting with no error message pop.

**Comment by rxaviers** [comment]
Hi @lidanbj,

Please, can you send a PR adding your failing case as a test case? Thanks.

PS: react-globalize has some additional features on top of our message module, which we should bring over here, for instance #575

**Comment by rxaviers** [comment]
Closing... We can reopen if we have additional details.
