### ISSUE TITLE
Get localized time zone names by time zone ID?

### ISSUE THREAD

**Issue by mj1856** [globalizejs/globalize#673]
I see that the Globalize date module has some functionality that relies on `timeZoneNames.json`.  Part of the data in these files is to support the rules defined in [Part 4 Section 7 of the TR35 spec](http://www.unicode.org/reports/tr35/tr35-dates.html#Using_Time_Zone_Names), which are used to determine the localized display name of a given time zone.

For example, given `America/Los_Angeles`, and `en-US`, I should be able to get back:
```json
{
    "generic": "Pacific Time",
    "standard": "Pacific Standard Time",
    "daylight": "Pacific Daylight Time"
}
```
Is this something that Globalize can do today and I'm just not finding it in the documentation?  If not, is it planned for a future release?

Thanks,
Matt

**Comment by rxaviers** [comment]
Hi @mj1856, globalize doesn't fully support timezone.
- What's supported: #202
- What's not supported: #340

I'm closing your issue in favor of the ones above. Feel free to add comments there. Thanks

**Comment by ravalibusetty1991** [comment]
Hi, just checking again. I'm really in need of a good library in Javascript which will give me localized timezone display names. For example, "Pacific Standard Time" when I pass in "America/Los_Angeles" and "en-US". Is this supported in globalize?

**Comment by kborchers** [comment]
I don't know if it's exactly what you need but you might want to check out some combination of Globalize, Moment Timezone and/or Spacetime.

https://momentjs.com/timezone/
https://github.com/smallwins/spacetime

**Comment by rxaviers** [comment]
All, globalize 1.3.0 does fully support IANA/Olson time zones 😄 (currently, use globalize@1.3.0-rc.0).

@rajavelmani, see [Using time zones examples here:

```js
// Requires Globalize 1.3.0 (globalize@1.3.0-rc.0)
Globalize.loadTimeZone( require( "iana-tz-data" ) );

Globalize.locale( "en" );

Globalize.dateFormatter({ datetime: "medium", timeZone: "America/Los_Angeles" })( new Date() );
// > "Nov 1, 2010, 12:55:00 PM"

Globalize.dateFormatter({ datetime: "medium", timeZone: "America/Sao_Paulo" })( new Date() )
// > "Nov 1, 2010, 5:55:00 PM"

Globalize.dateFormatter({ datetime: "full", timeZone: "Europe/Berlin" })( new Date() )
// > "Monday, November 1, 2010 at 8:55:00 PM Central European Standard Time"
```

If you are only looking for displaying the time zones names only, one approach is to use this:

```js
var fmt = Globalize.dateFormatter({ raw: "zzzz", timeZone: "America/Los_Angeles" });
fmt( new Date( 2017, 0, 1 ) ); // > 'Pacific Standard Time'
fmt( new Date( 2017, 7, 1 ) ); // > 'Pacific Daylight Time'
```

You can use any [CLDR Zone pattern](http://www.unicode.org/reports/tr35/tr35-dates.html#dfst-zone).

**Comment by rxaviers** [comment]
> https://momentjs.com/timezone/

Moment is a great library, but unfortunately it doesn't support CLDR. Globalize 1.3.0, which supports CLDR, now supports time zone. So basically using Globalize you have full IANA support with the strength of CLDR for i18n.

> https://github.com/smallwins/spacetime

A much smaller library (0.6KB), if you need to manipulate time zone dates (no i18n), is https://github.com/rxaviers/zoned-date-time (used under the hoods by globalize).

**Comment by rxaviers** [comment]
It's worth to mention that a big concern when using time zones + i18n is the **final size** of your bundles...

On Globalize, you can take advantage of the Globalize Compiler. For example, let's say you are serving a content in English and for America/Los_Angeles time zone for example using this formatter:

```js
var dateWithTimeZoneFormatter = Globalize.dateFormatter({
  datetime: "full",
  timeZone: "America/Los_Angeles"
});
```

The production final size of that will be:

| filename | minified+gzipped size |
| --- | --- |
| i18n/en.js | 1.7KB |
| core+number+date globalize runtime lib | 7.0KB | 

See globalize [compiler example](https://github.com/globalizejs/globalize/tree/master/examples/globalize-compiler) or [app-npm-webpack example](https://github.com/globalizejs/globalize/tree/master/examples/app-npm-webpack) for details.

**Comment by kborchers** [comment]
This was all very helpful and detailed, @rxaviers. Thanks!!
