### ISSUE TITLE
Globalize changes Time delimiter despite repository?!

### ISSUE THREAD

**Issue by draza67** [globalizejs/globalize#674]
I can't uderstand why and how this happens, but looks like a bug. JSON repository seems ok, but time delimiter is persistently dot!

Take a look at StackOverflow I wrote already:

http://stackoverflow.com/questions/41671500/globalize-cldr-globalize-formatdatenew-date-datetimelong-resulted

**Comment by rxaviers** [comment]
I've replied there http://stackoverflow.com/a/41681149/798133. Implementation is correct.
