### ISSUE TITLE
Unsafe JSON.stringify in runtimeKey()

### ISSUE THREAD

**Issue by ruslansavenok** [globalizejs/globalize#677]
Different browsers or sites with polyfills has different implementation of `JSON.stringify`, this causes different results for `runtimeKey()` between node env, which compiled code and the browser.

For example:
`JSON.stringify(['minute', {}])` produces: `"["minute",{}]"` or `""[\"minute\",{}]""`

**Comment by rxaviers** [comment]
Hi @ruslansavenok, thanks for your input. Please, do you have additional details about your statement? I'd like to see some examples of browsers vs. different outputs. Thanks

**Comment by rxaviers** [comment]
Closing... We can reopen if we have additional details.
