### ISSUE TITLE
Date format to parts

### ISSUE THREAD

**Issue by rxaviers** [globalizejs/globalize#678]
**Context**

Formatter is designed to provide an opaque string as an output that is not meant to be manipulated by the consumer, which makes impossible for UX/design using rich formatting, e.g., `"May <strong>05</strong> 2014"`, `"09:49 <i>pm</i>"`, and `"<strong>Monday</strong>, 09/12/2015"`.

**Goal**

Expose format to parts similarly to Ecma-402 Intl.DateTimeFormat.prototype.formatToParts().

**References**

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts
- https://github.com/tc39/ecma402/issues/30
- https://tc39.github.io/ecma402/#sec-Intl.DateTimeFormat.prototype.formatToParts

**Comment by rxaviers** [comment]
Some API ideas

 1. Add `option.parts` to dateFormatter (and formatDate) that takes true or false (default). Downside: return different types depending on the options...
 1. Add new function pairs: `dateToPartsFormatter` and `formatDateToParts`. Downside: additional work for static compiler.
 1. Add a function on the returned formatter, e.g., dateFormatter() -> fn.toParts(). Downside: very hacky.

**Comment by rxaviers** [comment]
For the record, @jzaefferer and I have discussed these options and we leaned towards option 2. It seems the one the fits the best for globalize in a way that keeps API simple. Suggestions and ideas are welcome...

**Comment by kborchers** [comment]
I am by no means an expert here but reviewing the information you have provided, I would also lean toward option #2 if that helps at all.

**Comment by rxaviers** [comment]
Thank you @kborchers, it definitely helps.
