### ISSUE TITLE
Currency format to parts

### ISSUE THREAD

**Issue by rxaviers** [globalizejs/globalize#679]
**Context**

Formatter is designed to provide an opaque string as an output that is not meant to be manipulated by the consumer, which makes impossible for UX/design using rich formatting, e.g., `"<strong>EUR</strong> 35"`.

**Goal**

Expose format to parts similarly to Ecma-402 Intl.DateTimeFormat.prototype.formatToParts().

**References**

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat/formatToParts
- https://github.com/tc39/ecma402/issues/30
- https://tc39.github.io/ecma402/#sec-Intl.DateTimeFormat.prototype.formatToParts

**Comment by patch** [comment]
`currencyToPartsFormatter` would be very useful for several projects that I'm working on, not just for access to the currency sign but also for access to the different number parts for stylizing dollars and cents (and their equivalents in other currencies) in different formats.

**Comment by rxaviers** [comment]
@patch is anyone from your team willing to work on it? It's a straightforward change. This [diff can be used as baseline](https://github.com/globalizejs/globalize/compare/687207b396e52fb1be6678674fa48bb6860f9048...e4234a7baa761969dcb345f5725fbe8aed89101f) and I'd be available to guide.

**Comment by patch** [comment]
Potentially. I'll review the changes for `dateToPartsFormatter` and start out with the spec for `currencyToPartsFormatter`. Fortunately we now have a solid date-based part formatter to work from. (By the way, great new feature! Thanks!)

**Comment by rxaviers** [comment]
Excellent and thank you! :)

**Comment by TheDutchDevil** [comment]
Are there any updates on this? As we recently ran into this issue.

**Comment by rxaviers** [comment]
Hi @TheDutchDevil, this has stalled. Do you want to contribute this feature. It should be a straightforward additioanl and it can use date to parts as baseline as mentioned [above](https://github.com/globalizejs/globalize/issues/679#issuecomment-313478477). Thanks

**Comment by TheDutchDevil** [comment]
I would love to add it in, however, I just don't have the hours for it. :( Especially as the diff you linked appears to look quite involved.

**Comment by rxaviers** [comment]
Funny if not sad, we all would love to do a lot of things, the problem are the hours for them.
