### ISSUE TITLE
validateParameterTypeString is not a function error even though number.js is defined before date.js

### ISSUE THREAD

**Issue by number45** [globalizejs/globalize#681]
I'm getting the error validateParameterTypeString is not a function when trying to use parseDate.  Searching suggests this can occur when number.js is not imported before date.js however I am importing the files in the correct order.

`<script src="/scripts/customformvalidation/Globalize/cldr/cldr.js"></script>`
`<script src="/scripts/customformvalidation/Globalize/cldr/event.js"></script>`
`<script src="/scripts/customformvalidation/Globalize/cldr/supplemental.js"></script>`
`<script src="/scripts/customformvalidation/Globalize/globalize.js"></script>`
`<script src="/scripts/customformvalidation/Globalize/number.js"></script>`
`<script src="/scripts/customformvalidation/Globalize/date.js"></script>`

Regards.

**Comment by rxaviers** [comment]
I could not reproduce the bug. I tried https://gist.github.com/rxaviers/ac7c8e3ae9181d1a07654c84a8926b77.

Please, provide reproducible example, in which case we reopen the issue. Thanks
