### ISSUE TITLE
New v1.2.* returns 0 when number-parsing empty strings

### ISSUE THREAD

**Issue by samcic** [globalizejs/globalize#682]
See 

http://stackoverflow.com/questions/41748476/globalize-bug-in-new-v1-2-parsing-empty-string-returns-0

In short, there seems to be a regression in v1.2.* in that empty strings are now number parsed to 0 instead of NaN This seems rather non-intuitive, and I can't imagine it's intentional.

**Comment by rxaviers** [comment]
This is indeed a bug and a regression that needs to be fixed. Thanks for reporting it.
