### ISSUE TITLE
formatNumber returns NaN for 0, if max/minimumSignificantDigits is set

### ISSUE THREAD

**Issue by AndreR** [globalizejs/globalize#706]
Hello,

If you call the following function, it returns "NaN %":

`Globalize.formatNumber(0, {style:'percent',minimumSignificantDigits: 1,maximumSignificantDigits: 3})`

If you leave out the significant digits settings, it returns an empty string, as I would expect.

**Comment by rxaviers** [comment]
Thanks for reporting this bug.
