### ISSUE TITLE
Support for non-gregorian calendars

### ISSUE THREAD

**Issue by yegane17** [globalizejs/globalize#711]
hi. is still Globalize.js 1.x not supporting jalali calendar?
thnks for your attention

**Comment by rxaviers** [comment]
It's not supported, but PRs are welcome. Closing in favor of #320.
Please, just let me know if you have any other questions.

**Comment by yegane17** [comment]
i have a calendar that is in gregorian type. i use devxtreme component and its not supporting jalali or islamic calendar. and now i am confuse that how can i use persian calendar with globalize.js and cldr.js in devextreme component
thanks for your helping

**Comment by rxaviers** [comment]
Your question wasn't very clear to me, but I can give you some information: Globalize 1.x doesn't support non-gregorian calendars. This was a regression compared to Globalize 0.x.

**Comment by yegane17** [comment]
could you please show me an example that use globalization 0.x and a calendar in islamic format? thank you

**Comment by rxaviers** [comment]
0.x documentation can be found [here](https://github.com/globalizejs/globalize/tree/v0.1.1), but note it's deprecated. For additional questions, please use StackOverflow. Thanks
