### ISSUE TITLE
creating dictionary

### ISSUE THREAD

**Issue by yegane1994** [globalizejs/globalize#716]
i am using globalize 1.1.1 .
creating dictionary by this code : localization.loadMessages({de: { "name": "Vorname"}})
and use it by this code :Globalize.formatMessage("name")
and got this error Globalize.formatMessage is not a function.
am i using wrong version or its what? it is so confusing that in every version your names is going to change and when we are using them we got so many names that are not clear .

**Comment by rxaviers** [comment]
Did you load the message module? Please see our examples as a baseline https://github.com/globalizejs/globalize/tree/master/examples.

If you still think there's an issue, please provide a way to reproduce it and I will reopen. Thanks
