### ISSUE TITLE
Error using "MMMM" with skeleton in date formatting.

### ISSUE THREAD

**Issue by jsearles** [globalizejs/globalize#718]
This code generates an error using version 1.2.3 of Globalize:

```js
Globalize.dateFormatter({ skeleton: "MMMM" })(new Date())
```

The error is "E_UNSUPPORTED: Unsupported {"feature":"year pattern `u`"}." which occurs because in the dateExpandPattern this line turns the pattern into "undefined at undefined":

```js
				result = combineDateTime( type,
					cldr.main([
						"dates/calendars/gregorian/dateTimeFormats/availableFormats",
						dateSkeleton
					]),
					cldr.main([
						"dates/calendars/gregorian/dateTimeFormats/availableFormats",
						timeSkeleton
					])
				);
```

This happens in Chrome (v59), Firefox (v53), and Node (v4.4.5).

**Comment by rxaviers** [comment]
Thanks for filing this issue. This is fixed in master (and in 1.3.0-alpha.3), coming in 1.3.0 soon.
