### ISSUE TITLE
Example error on loadTimeZone

### ISSUE THREAD

**Issue by Countraya** [globalizejs/globalize#736]
I had just tried to follow your instruction on the plain javascript example https://github.com/globalizejs/globalize/tree/master/examples/plain-javascript

When I test there is an error on loadTimeZone :

Uncaught TypeError: Globalize.loadTimeZone is not a function at index.html:285

Do I need to add any other dependencies ?

**Comment by rxaviers** [comment]
The error you got suggests you have downloaded **globalize@1.2.3** (the latest stable) to be used with the example available on the **master** branch (currently the 1.3.0-alpha.6 pre-release).

**Comment by rxaviers** [comment]
Please, use the example with the corresponding globalize version and you should be good. Thanks for filing this issue.
