### ISSUE TITLE
Why it does not work?

### ISSUE THREAD

**Issue by userblyatb1** [globalizejs/globalize#739]
Globalize.load(
                $.getJSON('/js/cldr/supplemental/numberingSystems.json'),
                $.getJSON('/js/cldr/supplemental/likelySubtags.json'),
                $.getJSON('/js/cldr/main/ru/numbers.json'),
            );
            Globalize.locale('ru');

Error: E_MISSING_CLDR: Missing required CLDR content `main/ru/numbers/defaultNumberingSystem`.

**Comment by rxaviers** [comment]
Please, try to use the examples in this repo to reproduce this issue and add a new comment with steps to reproduce. Thanks
