### ISSUE TITLE
numberFormatter method returns  exponential view of number

### ISSUE THREAD

**Issue by KhrystynaPopadyuk** [globalizejs/globalize#750]
Hi,

I have numeric value  2e-7. In order to display it to user I use numberFormatter method (minimumIntegerDigits = 1, minimumFractionDigits = 0, maximumFractionDigits = 10) and as result I expect to get something like "0,0000002" but I get "2e-7".
How can I avoid exponential notation when format such values?

Thanks

**Comment by rxaviers** [comment]
Hi, this is a bug and [this code](https://github.com/globalizejs/globalize/blob/master/src/number/format/integer-fraction-digits.js#L48) needs fix.

**Comment by rxaviers** [comment]
This could be useful https://stackoverflow.com/a/1685917/798133

**Comment by rxaviers** [comment]
Deleting this: This could be useful https://stackoverflow.com/a/1685917/798133

**Comment by rxaviers** [comment]
We needed to use this instead: 

```js
2e-7.toFixed(7)
'0.0000002'
```

**Comment by rxaviers** [comment]
This is fixed! Will be release in 1.3.0.
