### ISSUE TITLE
Date and time separators

### ISSUE THREAD

**Issue by brunis** [globalizejs/globalize#760]
Hi, it's been a true nightmare getting this non-standardized stuff working. Not only is it non-standard, it refuses standards and replaces them with non-standards.

First of all most of the CLDR data is wrong, that is not your problem, i will report that to unicode.

But i'd like to request some more flexibility in setting up Globalize, like configuring separators, so i can get the standards right.

Eg. for danish, this is the standard 27-11-2017 11:23, but CLDR thinks it's 27/11/2017 11.23 (notice the dot time separator).

So to circumvent this (and to be future proof) i create and merge my own json gregorian formats that override the non-standard unicode data. All dashes for date separators and all colons for time separators, but what does Globalize do?  It replaces my colons with dots anyway! .. seriously? wtf!

I have confirmed the formats being correct by checking from browser console:
Globalize("da").cldr.main("dates/calendars/gregorian/dateTimeFormats/availableFormats")

All dateTime formats are correct, but the formatter still outputs 23.11
Globalize.formatDate(new Date(), { datetime: "short" }) get's it wrong, even Globalize.formatDate(new Date(), { raw: "HH:mm" }) get's it wrong!

**Comment by rxaviers** [comment]
Globalize has no data... All it knows comes from the CLDR json you pass in. Can you share your overrides with me in a gist?

**Comment by brunis** [comment]
It just boggles the mind that they hardcode the wrong separator. There are so many valid ones, so why hardcode the wrong one and refuse to accept an alternative? ..it boggles the mind.

**Comment by rxaviers** [comment]
Also, please share the unicode trac issue you filed?

**Comment by brunis** [comment]
I'll get back to you when i have something from unicode.

Until then can you explain why: Globalize.formatDate(new Date(), { raw: "HH:mm" }) replaces ":" with "." ?

Did i miss the point of raw ?

**Comment by brunis** [comment]
From googling it seems the Unicode data is correct, it is just incompatible with .NET because Microsoft uses their own custom formats, so i wont be taking this up with unicode after all and i doubt any attempts at getting Microsoft to change their ways about standards is a wasted effort.

**Comment by rxaviers** [comment]
> Until then can you explain why: Globalize.formatDate(new Date(), { raw: "HH:mm" }) replaces ":" with "." ?

You could either override [timeSeparator symbol](https://github.com/unicode-cldr/cldr-numbers-modern/blob/master/main/da/numbers.json#L29) or escape it in your pattern like `':'`.

Given your statement, I'm closing this issue. Feel free to post additional comments if you think we should keep this open.
