### ISSUE TITLE
Rounding of negative numbers behaves differently in 1.+

### ISSUE THREAD

**Issue by jrsearles** [globalizejs/globalize#765]
I'm not sure if this is intentional, but the behavior has changed. 

For example:

```js
// pre 1.0
Globalize.format(-1.445, "n2")
// yields -1.45

// 1.+
Globalize.formatNumber(-1.445, { minimumFractionDigits: 0, maximumFractionDigits: 2 })
// yields -1.44
```

When the number is positive they both behave the same (1.45)

**Comment by rxaviers** [comment]
Hi @jrsearles, Globalize 1.x should follow CLDR specs (UTS#35), independent of 0.x behavior. The number formatter uses round by default. Though, you can modify the rounding function if you prefer to: https://github.com/globalizejs/globalize/blob/master/doc/api/number/number-formatter.md#optionsround

Closing as not an issue...

PS: Note this:

```js
Math.round(144.5)
// > 145
Math.round(-144.5)
// > -144
```

**Comment by jrsearles** [comment]
Is the rounding behavior spelled out in the CLDR specs?

I don't think the rounding behavior's exposed quite allow for the prior behavior. At least not without some heavy-handed introspection. (IE, determining if the number is negative and determining if the digit one beyond the scale is 5, and then dynamically selecting floor in those cases.)

I should be fine with this being closed though - i think i can get by with this behavioral difference. I just wanted to understand if it was intentional.
