### ISSUE TITLE
currencyFormatter is reversed, or, should have an option to be

### ISSUE THREAD

**Issue by netpoetica** [globalizejs/globalize#770]
When you have a currency intended to be formatted $0.00, the expectation is

```
formatter(1)
"$0.01"
formatter(11)
"$0.1"
formatter(111)
"$1.11"
formatter(1111)
"$11.11"
formatter(11111)
"$111.11"
```

but this library behaves like so:

```
formatter(1)
"$1.00"
formatter(11)
"$11.00"
formatter(111)
"$111.00"
formatter(1111)
"$1,111.00"
formatter(11111)
"$11,111.00"
```

If you navigate to any banking app, etc, you will see that it uses the accounting style of numeric input - which is that you always fill the decimals in first. This is what I have seen across the web.

It appears that in order for the currencyFormatter to ever properly use decimals, the end user *must* type their locale's decimal symbol. I believe this is a very strange behavior.

I assumed I could achieve this by either selecting `style: 'accounting'`, or, that if I were to specify the minimumFractionDigits it would enforce entering the decimal.

I think a common expectation would be this:

```
Globalize.locale('en');
const formatter = Globalize.currencyFormatter('USD', {
	minimumFractionDigits: 2
});

formatter(100);
> $1.00

Globalize.locale('en');
const formatter = Globalize.currencyFormatter('USD', {
	minimumFractionDigits: 1
});

formatter(100);
> $10.0

Globalize.locale('en');
const formatter = Globalize.currencyFormatter('USD', {
	minimumFractionDigits: 0
});

formatter(100);
> $100
```

Any thoughts on this? [Accounting.js](http://openexchangerates.github.io/accounting.js/) is a good example of this behavior.

Curious to know if I am the only one who thinks this? Maybe I am unclear on the intention of the currencyFormatter?

**Comment by netpoetica** [comment]
Alternatively, if globalize.js had a mechanism to just output what the symbol, code, decimal separator and thousands separator, an end-user could get the local information from Globalize and then just use their own formatter or a lib like accountingjs.

Ideally

```
Globalize.locale('en');
const formatter = Globalize.currencyFormatter('USD', {
	minimumFractionDigits: 2
});

console.log(formatter.decimalSeparator)
> .
console.log(formatter.thouandsSeparator)
> ,
console.log(formatter.sybol)
> $
console.log(formatter.code)
> USD
console.log(formatter.precision)
> 2
```

**Comment by rxaviers** [comment]
> When you have a currency intended to be formatted $0.00, the expectation is
> ```js
> formatter(1)
> "$0.01"

Different currencies have different number of decimal digits normally formatted. ([spec](http://www.unicode.org/reports/tr35/tr35-numbers.html#Supplemental_Currency_Data)).

In your suggestion, how would your application know in advance which precision would the formatter take? It seems like you still have the same problem.

@netpoetica suggestions seems like a good approach to me to solve this problem. Closing this issue, superseded by #605
