### ISSUE TITLE
QUESTION: Better Plain JS example

### ISSUE THREAD

**Issue by caraya** [globalizejs/globalize#781]
Is there a complete example of Globalize.js using Plain Javascript that shows how to load specific CLDR data now that cultures are no longer supported in Globalize. The current plain Javascript example loads the data for you which makes it hard to figure out how to do it yourself.

**Comment by rxaviers** [comment]
https://github.com/globalizejs/globalize/blob/master/doc/cldr.md#how-do-i-load-cldr-data-into-globalize

Feel free to post additional comments (and I reopen it) if you find bugs in the docs. For questions, please use [SO](https://github.com/globalizejs/globalize/#contributing). Thanks
