### ISSUE TITLE
localization problem for tr-TR

### ISSUE THREAD

**Issue by slhmrt** [globalizejs/globalize#784]
in .html
<script src="~/Scripts/globalize.js"></script>
<script src="~/Scripts/globalize/lib/cultures/globalize.culture.tr-TR.js"></script>
<script src="~/Scripts/globalize/number.js"></script>

error : Uncaught TypeError: Globalize.addCultureInfo is not a function

added below code in globalize.js (many people wrote this as workaround)
Globalize.addCultureInfo = function (cultureName, baseCultureName, info) {
    var base = {},
[JS.zip](https://github.com/globalizejs/globalize/files/1461709/JS.zip)

            isNew = false;
    if (typeof cultureName !== "string") {
        // cultureName argument is optional string. If not specified, assume info is first
        // and only argument. Specified info deep-extends current culture.
        info = cultureName;
        cultureName = this.culture().name;
        base = this.cultures[cultureName];
    } else if (typeof baseCultureName !== "string") {
        // baseCultureName argument is optional string. If not specified, assume info is second
        // argument. Specified info deep-extends specified culture.
        // If specified culture does not exist, create by deep-extending default
        info = baseCultureName;
        isNew = (this.cultures[cultureName] == null);
        base = this.cultures[cultureName] || this.cultures["default"];
    } else {
        // cultureName and baseCultureName specified. Assume a new culture is being created
        // by deep-extending an specified base culture
        isNew = true;
        base = this.cultures[baseCultureName];
    }
    this.cultures[cultureName] = extend(true, {},
            base,
            info
    );
    // Make the standard calendar the current culture if it's a new culture
    if (isNew) {
        this.cultures[cultureName].calendar = this.cultures[cultureName].calendars.standard;
    }
};

after that new error: Uncaught TypeError: Cannot read property 'default' of undefined

i changed call function parameter from 'default' to 'tr-TR' in globalize.culture.tr-TR.js and tried again

new error: Uncaught TypeError: Cannot read property 'default' of undefined

**Comment by rxaviers** [comment]
Hi thanks for filing the issue, but globalize 0.x is deprecated and not supported.

**Comment by slhmrt** [comment]
Globalize v1.3.0
