### ISSUE TITLE
Improve documentation, please, it's a nightmare

### ISSUE THREAD

**Issue by jmmoya** [globalizejs/globalize#787]
Please, improve your documentation. I saw some Issues complaining about documentation too and I agree. It's a nightmare to configure if you are only allowed to use simple javascript, not node, not bower, etc.

I'm lost, I'm trying to use the library in ASP.NET MVC5. I tried downloading files from Github, and from NuGet, and they are completly diferent, even some files aren't included.

I downloaded all modules from cldr, I watched all the examples, trying to extract something in common as a minimal setup, but everything is different in all examples, not just how to import files.

Could you please make a minimal setup just copying files, and the instruction to initialize?

Plain Javascript example is the worst, writing manually the complete localization configuration.

Could you make the same exact example in all the ways?

**Comment by rxaviers** [comment]
PRs are welcome.
