### ISSUE TITLE
Mention Slack community in readme and contributing files

### ISSUE THREAD

**Issue by jzaefferer** [globalizejs/globalize#798]
Assuming there's a way to join the Slack community without an invitation, it should be mentioned both in the README and in the Contributing.md (and replace the IRC link?).

**Comment by rxaviers** [comment]
Would you like to submit a PR please?

**Comment by jzaefferer** [comment]
https://globalizejs.slack.com says "Don't have an account on this workspace yet? Contact the workspace administrator for an invitation"

It doesn't say who the admin is or how to contact them. I guess its you, but maybe there's some kind of invite link? I've seen those for other workspaces, but I don't know how they work.

**Comment by rxaviers** [comment]
I just set you as admin too since we plan to use that officially (and not as an experiment as done so far).

It's possible to create an invite link that never expires... Publish that in our docs?

**Comment by jzaefferer** [comment]
> It's possible to create an invite link that never expires... Publish that in our docs?

As long as its possible to manually expire (disable?) that link, sure.

I've looked for that feature, but couldn't find anything.

**Comment by rxaviers** [comment]
> As long as its possible to manually expire (disable?) that link, sure.

> I've looked for that feature, but couldn't find anything.

Yeap, I created one and saw it's possible to deactivate it.

**Comment by jzaefferer** [comment]
Alright. If you still want me to do the PR, I'll need the actual link :-)

**Comment by rxaviers** [comment]
Sure we can use this one https://join.slack.com/t/globalizejs/shared_invite/enQtMjk4OTUwNzM1Nzk0LTk2YmY0YjY3Yzk4YzU3M2NkMDZjNThlNzcwNTkyNGJhNDhiNjdkMWUyN2Q2MjVmNTk0ZjkyNGQ3MWEyNzNmMWU
