### ISSUE TITLE
Why globalize-compiler needs different globalize includes (npm vs. NuGet)?

### ISSUE THREAD

**Issue by sunsande** [globalizejs/globalize#799]
I've posted the question already on stackoverflow ([Link to SO](https://stackoverflow.com/questions/48170071/why-globalize-compiler-needs-different-globalize-includes-npm-vs-nuget)), but didn't get answer, so I hope to get it here:

in short the NuGet version of globalize in Visual Studio installs only the globalize.js + globalize folder.
The npm version of globalize (installed as dependency of globalize-compiler) installs globalize-runtime.js and the globalize-runtime folder.
The files produced from the globalize-compiler work only with the globalize-runtime.js

Could someone explain why is that and eventually how to get globalize-runtime from NuGet - it would make the build process easier. Otherwise one has to copy the globalize-runtime from the globalize-compiler dependencies folder to the projects folder manually.
I also hope I am wrong and there is another proper way to get this done.

Best Regards,
Alex

**Comment by rxaviers** [comment]
Thanks for raising your question in here too, but SO is indeed the proper tool/channel for that. Thanks
