### ISSUE TITLE
No parsing support for number compact option

### ISSUE THREAD

**Issue by Kirill486** [globalizejs/globalize#800]
Hi, guys)
I spent some time trying to get my number formatted as thousands and millions and billions and so on. 
This wasn't that much an issue in previous version (0.x.x).
I'm about to give up.
Could you possibly somehow guide me out?
After I faced a failure with the 'compact' option, I went to see number putterns on http://cldr.unicode.org/translation/number-patterns#TOC-Pattern-Characters
They don't work either.
I tried:
<code>
Globalize('en').formatNumber(100000, {style: 'decimal'})
</code> <br>
"100,000" <br>
<code>
Globalize('en').formatNumber(100000, {raw: '00K'}) 
</code> <br>
"100000K" <br>
<code>
Globalize('en').formatNumber(100000, {raw: '#,##0%'}) 
</code>  <br>
"10,000,000%" <br>
<code>
Globalize('en').formatNumber(100000, {compact: 'short'}) 
</code> <br>
"100,000" <br>
<code>
<code>
Globalize('en').formatNumber(100000, {compact: 'long'}) 
</code> <br>
"100,000" <br>
<code>
Globalize('en').formatNumber(1, {style: 'percent'})
</code> <br>
"100%" <br>
This is the only one that work correctly.

What i need is: format my numbers using styles listed in 'decimalFormats' section of the number.json
Is that possible?

**Comment by rxaviers** [comment]
Please, which globalize version are you using?

**Comment by Kirill486** [comment]
I use v 1.1.1

**Comment by rxaviers** [comment]
Please, test it using `1.4.0-alpha.0`?

**Comment by rxaviers** [comment]
`1.4.0-alpha.0` is the version where you will find compact support.

**Comment by Kirill486** [comment]
Even in newer version this functionality seem not working correctly.
<code>
var formatteden = Globalize('en').numberFormatter({compact: "long"})(100000)
</code><code>
undefined
</code><code>
formatteden
</code><code>
"100 thousand"
</code><code>
var parceden = Globalize('en').numberParser({compact: "long"})(formatteden)
</code><code>
undefined
</code><code>
parceden
</code><code>
NaN
</code>

And is there a way specify the format (thousands or millions or billions)?

**Comment by rxaviers** [comment]
Thanks for checking, reopening then...

**Comment by Kirill486** [comment]
I came to conclusion, that normally you wouldn't parse compact numbers(it has a hudge unaccuracy, even billions is an option), it's just worth mentioning in documentation.

**Comment by rxaviers** [comment]
Clarifying this issue... Formatting works fine [1], but there's no parsing support for number compact option.

1:
```js
Globalize('en').numberFormatter({compact: "long"})(100000)
// > '100 thousand'
```
