### ISSUE TITLE
Reuse pluralGenerator for messageFormatter

### ISSUE THREAD

**Issue by bingzheyuan** [globalizejs/globalize#817]
https://github.com/globalizejs/globalize/blob/67b75feb6d597801ec94e571424b49f26711ba0b/src/message.js#L85-L88
Message Formatter seems to generate a plural Generator for every formatter, should we reduce this behaviour? We should have a default one (if we have a globalize instance) or we don't need it at all, not every message needs a plural generator.

**Comment by rxaviers** [comment]
By using globalize-compiler, this is going to be cached...

A generic way of solving this for the non-compiled case is #470

**Comment by rxaviers** [comment]
Closing this in favor of https://github.com/globalizejs/globalize/pull/470#issuecomment-405654057
