### ISSUE TITLE
Get strange result in new version

### ISSUE THREAD

**Issue by dxvladislavvolkov** [globalizejs/globalize#825]
I used the old version of this package. After the update, I began to get different results when parsing numbers.
You can see the following examples:
1. globalize 1.1.1 I get the right result ("1.2" => 12)
http://plnkr.co/edit/tkZk2rLEsEEOz3siUW6i?p=preview

2. globalize 1.3.0 I get the wrong result ("1.2" => NaN)
http://plnkr.co/edit/NRFJISLDoyCnfTY93Bkg?p=preview

**Comment by rxaviers** [comment]
Correct, in 1.3.0 that parsing bug was fixed. Note `.` isn't a decimal separator in `de`. It would be considered a grouping separator if there were three digits after it.

https://runkit.com/embed/mav67vxk8awb
