### ISSUE TITLE
Looking for advice (strategy)

### ISSUE THREAD

**Issue by dlplenin** [globalizejs/globalize#829]
We have 3 projects:

- 1 MEAN stack
- 1 MERN stack (web)
- 1 MERN stack (ios & android)

We want to avoid duplicated words (Messages => loadMessages) among projects (centralize resources), but also keep  the funcionalities like formatRelativeTime, formatCurrency, etc.

So we are thinking in building a new project to handle internationalization and localization for our projects.

Do you think is it possible with “globalize”? Any idea how to proceed?

Any help will be appreciated

**Comment by rxaviers** [comment]
I think so... Having said that, this is out of scope of globalize issues. Elaborate your needs and file issues if you need a new feature or if something is broken, but be specific. Thanks
