### ISSUE TITLE
"Hello World (plain JavaScript)" demo does not work

### ISSUE THREAD

**Issue by gingerbbm** [globalizejs/globalize#832]
I followed the very simple instructions at https://github.com/globalizejs/globalize/tree/master/examples/plain-javascript but the Globalize zip doesn't contain the required _dist_ folder and contents.

**Comment by rxaviers** [comment]
On that README.md we have:

> 1. Click at [Globalize releases tab](https://github.com/rxaviers/globalize/releases).

The correct link is: https://github.com/globalizejs/globalize/releases

Would you like to update it? Thanks

**Comment by gingerbbm** [comment]
Tried it and it works - thanks. I would gladly update the .MD but no idea what the process is to do that. Give me a clue and I'll try.

**Comment by rxaviers** [comment]
Excellent. Sure, you can [even use github interface to edit the file](https://help.github.com/articles/editing-files-in-your-repository/).

When naming the commit, please make sure it begins with "Docs: ".

Let me know if you have further questions. Thanks

**Comment by gingerbbm** [comment]
OK, it's done - I think. I did a pull request. Not sure what happens next... let me know if I did something wrong. Thanks!

**Comment by rxaviers** [comment]
Thank you! PR #833 is now merged.
