### ISSUE TITLE
where can I get globalize.js?

### ISSUE THREAD

**Issue by helium73** [globalizejs/globalize#842]
It seems globalize.js isn't anywhere to be found.   I'm lost here.  There are a 1000 files and not one of them appears to be globalize.js.   The jquery UI date spinner has globalize.js as a dependency so the example doesn't work.    I'm sorry if this seems like a stupid question but I just need a globalize.js that works the way jquery ui expects it to.

**Comment by rxaviers** [comment]
Questions are better suited for stackoverflow ([instructions](https://github.com/globalizejs/globalize#contributing)). Issues should be used to report bugs or discuss new features. Please, could you post your question there? Thanks
