### ISSUE TITLE
Slack invite link in README has expired

### ISSUE THREAD

**Issue by robaw** [globalizejs/globalize#887]
I was looking to contribute a change and wanted to chat about it, but looks like the slack link to sign up to the globalize workspace has expired, could someone take a look and generate a new one?

**README:**
![image](https://user-images.githubusercontent.com/38808938/76744930-ebe4f100-676c-11ea-981c-8a232f84ebad.png)

**Slack Error:**
![image](https://user-images.githubusercontent.com/38808938/76744965-fc956700-676c-11ea-9f0e-492e4f8a57ef.png)

**Comment by rxaviers** [comment]
Thanks for reporting.

**Comment by rxaviers** [comment]
Link has been updated and should work now (confirmed). Please, retry and let me know if you find any problems.
