### ISSUE TITLE
numberParser not returning the expected value for locale "sh" or serbian language

### ISSUE THREAD

**Issue by PratikshaKumbhare** [globalizejs/globalize#925]
Hello,

We are using the latest version of globalize.js
For serbian or locale "sh",when we are trying to parse a number, For ex: 83, the number is converted to 83000.
 
The numberParser returns wrong value here for locale "sh".

In Serbian , (comma) is used as decimal separator which is same in the case of German.

![numberparser](https://user-images.githubusercontent.com/90914347/133924981-a99248c4-804c-415b-8252-3d051383ad59.png)

How this could be fixed? How can we get the correct output?

**Comment by rxaviers** [comment]
It seems like CLDR supports Croatian (`hr`), but not Serbo-Croatian (`sh`) [1]

```js
Globalize("hr").formatNumber(88.334)
// > '88,334'

Globalize("hr").parseNumber("88,334")
// > 88.334
1:
- This tells what's the likely language for HR: https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/likelySubtags.json#L1463
- There's https://github.com/unicode-cldr/cldr-numbers-full/tree/master/main/hr
- There isn't a https://github.com/unicode-cldr/cldr-numbers-full/tree/master/main/sh
- https://github.com/unicode-cldr/cldr-localenames-full/blob/master/main/en/languages.json for figuring out the locale names
- https://github.com/unicode-cldr/cldr-localenames-full/blob/master/main/en/territories.json for figuring out the region names
